# -*- coding: utf-8 -*-
"""_jogo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lGfHwQxijdH8yVEbLkVxyhYsQoNibWbG
"""

import sys, pygame, time, pandas as pd

class jogo(object): # classe para organizar variáveis (ou atributos) e métodos

  #### INICIALIZAÇÕES DE VARIÁVEIS ####

  # se IN_COLAB=True, o código foi executado no Colab, senão, no console
  IN_COLAB = 'google.colab' in sys.modules

  # cores
  GRAY = (232, 232, 232)
  RED = (255, 0, 0)
  GREEN = (0, 255, 0)
  BLUE = (0, 0, 255)
  BLACK = (0, 0, 0)
  WHITE = (255, 255, 255)

  largura, altura = 400, 600 # largura e altura da tela

  #### MÉTODOS ####
  def drawScreenColab(screen):
    '''
      Esse método vai salvar a tela do jogo em uma imagem e exibir no Colab
      Entrada: screen - tela do jogo
      Saída: exibir tela no Colab
    '''
    import cv2
    from google.colab.patches import cv2_imshow
    # conversões para mostrar a tela do pygame como uma imagem no OpenCV [cv2]
    view = pygame.surfarray.array3d(screen)
    # converte de (largura, altura, channel) [do pygame] para (altura, largura, channel) [do cv2]
    view = view.transpose([1, 0, 2])
    # converte do padrão rgb para bgr
    img_bgr = cv2.cvtColor(view, cv2.COLOR_RGB2BGR)
    # mostra image
    cv2_imshow(img_bgr)

  def drawScreen(screen, tempo=0):
    '''
      Esse método vai salvar a tela do jogo em uma imagem e exibir no Colab ou no Console
      Entrada: screen - tela do jogo
               tempo - tempo de exibição da imagen, se Colab
      Saída: exibir tela no Colab ou no Console
    '''
    pygame.display.update()

    if jogo.IN_COLAB: # para rodar o jogo neste Colab
        from google.colab import output

        jogo.drawScreenColab(screen)

        if tempo:
          time.sleep(tempo)
          output.clear()

    else: # para rodar o jogo no console

        if tempo > 0:
          time.sleep(tempo) # NÃO funciona python >= 3.9
        else:
            run = True
            while run:
              for event in pygame.event.get():
                if event.type == pygame.QUIT:
                  run = False

  ###################### Escrever texto ######################
  def render_text(screen, text, pos, basicFont, color, background_color):
    '''
      Esse método vai escrever um texto na tela do jogo
      Entrada: screen - tela do jogo
               text - texto a ser escrito
               pos - posição do texto
               basicFont - fonte do texto
               color - cor do texto
               background_color - cor de fundo do texto
      Saída: exibir texto no Colab
    '''
    text_surface = basicFont.render(text, True, color, background_color)
    # True = anti-aliasing = linhas suaves = diminui efeito escada
    textRect = text_surface.get_rect()
    textRect.center = pos  # Centraliza o retângulo nas coordenadas (new_x, new_y)
    # desenha texto na janela
    screen.blit(text_surface, textRect)

  ###################### Criar desenhos a partir de um CSV ######################
  def drawFrameFromCSV(df, title='Hello World!'):
    '''
      Esse método vai criar a tela principal do jogo
      Entradas: df - tabela CSV do pandas
                title - título do jogo
      Saída: retorna o objeto tela do pygame
    '''
    frame = df.query("objeto == 'frame'")
    largura, altura = frame['larguraX'][0], frame['alturaY'][0]
    cor = (frame['corR'][0], frame['corG'][0], frame['corG'][0])

    screen = pygame.display.set_mode((largura, altura))
    pygame.display.set_caption(title) # título do jogo (no console)

    # desenha o fundo
    screen.fill(cor)

    return screen

  def drawCarFromCSV(df, screen):
    '''
      Esse método vai criar na tela principal um box (representando um carro, por exemplo)
      Entrada: df - tabela CSV do pandas
               screen - tela do jogo
      Saída: retorna o objeto tela do pygame incluindo o box
    '''
    car = df.query("objeto == 'car'")

    x, y = int(car['posicaoX']), int(car['posicaoY'])

    largura, altura = int(car['larguraX']), int(car['alturaY'])
    cor = (int(car['corR']), int(car['corG']), int(car['corB']))

    pygame.draw.line(screen, (150, 200, 200), (0, y - 3), (800, y - 3), 1)
    pygame.draw.line(screen, (150, 200, 200), (0, y + altura + 2), (800, y + altura + 2), 1)

    pygame.draw.rect(screen, cor, pygame.Rect(x, y, largura, altura))

    return screen

  def drawBoxFromCSV(df, screen):
    '''
      Esse método vai criar na tela principal um box
      Entrada: df - tabela CSV do pandas
               screen - tela do jogo
      Saída: retorna o objeto tela do pygame incluindo o box
    '''
    box = df.query("objeto == 'box'")

    x, y = int(box['posicaoX']), int(box['posicaoY'])

    largura, altura = int(box['larguraX']), int(box['alturaY'])
    cor = (int(box['corR']), int(box['corG']), int(box['corB']))

    pygame.draw.rect(screen, cor, pygame.Rect(x, y, largura, altura))

    return screen

  def drawLineFromCSV(df, screen):
    '''
      Esse método vai criar na tela principal uma linha
      Entrada: df - tabela CSV do pandas
               screen - tela do jogo
      Saída: retorna o objeto tela do pygame incluindo a linha
    '''
    line = df.query("objeto == 'line'")

    x1, y1 = int(line['posicaoX']), int(line['posicaoY'])

    x2, y2 = int(line['larguraX']), int(line['alturaY'])
    cor = (int(line['corR']), int(line['corG']), int(line['corB']))

    pygame.draw.line(screen, cor, (x1, y1), (x2, y2), int(line['utils']))

    return screen

  def drawImageFromCSV(df, screen):
    '''
      Esse método vai criar na tela principal uma imagem
      Entrada: df - tabela CSV do pandas
               screen - tela do jogo
      Saída: retorna o objeto tela do pygame incluindo a imagem
    '''
    import requests, io

    image = df.query("objeto == 'image'")

    x, y = int(image['posicaoX']), int(image['posicaoY'])

    url = image['utils'].to_numpy()[0]
    url = url[1:-1]
    r = requests.get(url)
    img = io.BytesIO(r.content)
    car = pygame.image.load(img)

    screen.blit(car, (x, y))
    pygame.display.flip()

    return screen

  def isPointInsideRect(x, y, rect):
    '''
    Método para verificar se o ponto (x, y) está dentro do retângulo
    Entradas: x, y - coordenadas do ponto
              rect - retângulo
    Saída: True se (x, y) está dentro de rect, ou False caso contrário
    '''
    if (x > rect.left) and (x < rect.right) and (y > rect.top) and (y < rect.bottom):
      return True
    else:
      return False

  def isRectsOverlap(rect1, rect2):
    '''
    Método para verificar se dois retângulos se tocam
    Entradas: rect1 - retângulo
              rect2 - retângulo
    Saída: True se rect1 toca rect2 (vice-versa), ou False caso contrário
    '''
    for r1, r2 in [(rect1, rect2), (rect2, rect1)]:
      # Verifique se pelo menos um dos cantos de r1 está dentro de r2
      if ((jogo.isPointInsideRect(r1.left, r1.top, r2)) or
          (jogo.isPointInsideRect(r1.left, r1.bottom, r2)) or
          (jogo.isPointInsideRect(r1.right, r1.top, r2)) or
          (jogo.isPointInsideRect(r1.right, r1.bottom, r2))):
        return True
    return False

  # método para escrever mensagem na tela
  def message_display(screen, text):
    def text_objects(text, font):
      textSurface = font.render(text, True, jogo.BLACK)
      return textSurface, textSurface.get_rect()

    largeText = pygame.font.Font('freesansbold.ttf', 115)
    TextSurf, TextRect = text_objects(text, largeText)
    TextRect.center = ((jogo.largura / 2), (jogo.altura / 2))
    screen.blit(TextSurf, TextRect)
    pygame.display.update()
    jogo.drawScreen(screen, 2)