# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DPwNqM0BAVT0S-3H03PbOKFb6hyXD-Wu
"""

import os
from contextlib import suppress
from pprint import pprint

import math
from enum import Enum
import copy
from copy import deepcopy
from collections import deque

import ipywidgets as widgets
from IPython.display import display, clear_output

from engine import Engine

class HeuristicsDashboard:
    def __init__(self, goat_heuristics_list, tiger_heuristics_list, width='500px'):
        """ Inicializa o dashboard com as listas de heurísticas para cabras e tigres. """
        self.goat_heuristics = self.create_heuristics(goat_heuristics_list, width)
        self.tiger_heuristics = self.create_heuristics(tiger_heuristics_list, width)
        self.output = widgets.Output()
        self.selected_goat_heuristics = []
        self.selected_tiger_heuristics = []
        self.engine = Engine(self.selected_goat_heuristics, self.selected_tiger_heuristics)

    def create_heuristics(self, description_list, width='500px'):
        """ Cria checkboxes para cada heurística. """
        return {desc: widgets.Checkbox(value=False, description=desc, layout=widgets.Layout(width=width)) for desc in description_list}

    def get_selected_heuristics(self):
        """ Coleta as heurísticas selecionadas. """
        self.selected_goat_heuristics = [key for key, checkbox in self.goat_heuristics.items() if checkbox.value]
        self.selected_tiger_heuristics = [key for key, checkbox in self.tiger_heuristics.items() if checkbox.value]

    def create_dashboard(self):
        """ Cria o layout do dashboard com as heurísticas. """
        goat_label = widgets.Label(value="Selecione as Heurísticas para Cabras:")
        tiger_label = widgets.Label(value="Selecione as Heurísticas para Tigres:")
        goat_column = widgets.VBox([goat_label] + list(self.goat_heuristics.values()))
        tiger_column = widgets.VBox([tiger_label] + list(self.tiger_heuristics.values()))
        return widgets.HBox([goat_column, tiger_column])

    def display_dashboard(self):
        """ Exibe o dashboard e trata a lógica do clique no botão. """
        def on_button_click(b):
            self.get_selected_heuristics()
            self.display_selected_heuristics()

        show_button = widgets.Button(description="Utilizar as heurísticas selecionadas", layout=widgets.Layout(width='250px', height='40px'), button_style='info')
        show_button.on_click(on_button_click)
        display(self.create_dashboard(), show_button)

    def display_selected_heuristics(self):
        """ Exibe as heurísticas selecionadas no console. """
        print("Heurísticas Selecionadas para Cabras:", self.selected_goat_heuristics)
        print("Heurísticas Selecionadas para Tigres:", self.selected_tiger_heuristics)

# Inicialização das heurísticas
goat_heuristics_list = [
    "Maximizar a Oportunidade de Movimentos",
    "Maximizar a Oportunidade de Espaços Fechados",
    "Minimizar Capturas",
    "Maximizar Proteção",
    "Posicionar no Centro",
    "Evitar Diagonais"
]

tiger_heuristics_list = [
    "Maximizar a Oportunidade de Movimentos",
    "Maximizar a Mobilidade dos Tigres",
    "Maximizar a Morte das Cabras",
    "Maximizar Capturas",
    "Ocupar Linhas Importantes",
    "Evitar Encurralamento",
    "Atacar em Grupo"
]