# -*- coding: utf-8 -*-
"""gameboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AzBBJPMzYse12xoUllfq1LG3pSy8J6Gn
"""

import pygame, os, subprocess

from _jogo import * # para usar os nossos métodos do pygame

class GameBoard:
  def __init__(self):

    self.jogo = jogo() # Cria uma instância de `jogo` dentro de `GameBoard`

    if self.jogo.IN_COLAB:
      os.environ["SDL_VIDEODRIVER"] = "dummy"

    # inicia um jogo
    pygame.init()

    jogo.largura,jogo.altura=600,600
    self.screen = pygame.display.set_mode((jogo.largura,jogo.altura))
    pygame.display.set_caption('Game: Bagha-Chall') # título do jogo (no console)

  def install_fonte(self):

        try:
            # Baixa a fonte "League Spartan" do Google Fonts
            subprocess.run(
                [
                    "wget",
                    "https://github.com/google/fonts/raw/main/ofl/leaguespartan/LeagueSpartan[wght].ttf",
                    "-O",
                    "/usr/share/fonts/truetype/LeagueSpartan.ttf",
                ],
                check=True,
            )

            # Atualiza o cache de fontes
            subprocess.run(["fc-cache", "-fv"], check=True)

            # Verifica se a fonte foi instalada corretamente
            result = subprocess.run(
                ["fc-list", "|", "grep", "LeagueSpartan"],
                check=True,
                text=True,
                capture_output=True,
                shell=True,
            )
            print("Fonte instalada com sucesso:\n", result.stdout)

        except subprocess.CalledProcessError as e:
            print("Erro ao instalar a fonte:", e)

  def game_layout(self):
    # desenha o fundo
    self.screen.fill(jogo.GRAY)

    # escreve texto branco em fundo azul
    # inicia as fontes
    # basicFont = pygame.font.SysFont(None, 40)
    self.basicFont = pygame.font.SysFont("/usr/share/fonts/truetype/LeagueSpartan.ttf", 55, bold=True, italic=True)
    self.basicFont_ = pygame.font.SysFont("/usr/share/fonts/truetype/LeagueSpartan.ttf", 40, bold=True, italic=True)

    jogo.render_text(self.screen, 'Game: Bagha-Chall', (self.jogo.largura/2, 40), self.basicFont, jogo.BLACK, jogo.GRAY)

    jogo.render_text(self.screen, 'A', (100, 100), self.basicFont_, jogo.BLACK, jogo.GRAY)
    jogo.render_text(self.screen, 'B', (200, 100), self.basicFont_, jogo.BLACK, jogo.GRAY)
    jogo.render_text(self.screen, 'C', (300, 100), self.basicFont_, jogo.BLACK, jogo.GRAY)
    jogo.render_text(self.screen, 'D', (400, 100), self.basicFont_, jogo.BLACK, jogo.GRAY)
    jogo.render_text(self.screen, 'E', (500, 100), self.basicFont_, jogo.BLACK, jogo.GRAY)

    jogo.render_text(self.screen, '1', (50, 150), self.basicFont_, jogo.BLACK, jogo.GRAY)
    jogo.render_text(self.screen, '2', (50, 250), self.basicFont_, jogo.BLACK, jogo.GRAY)
    jogo.render_text(self.screen, '3', (50, 350), self.basicFont_, jogo.BLACK, jogo.GRAY)
    jogo.render_text(self.screen, '4', (50, 450), self.basicFont_, jogo.BLACK, jogo.GRAY)
    jogo.render_text(self.screen, '5', (50, 550), self.basicFont_, jogo.BLACK, jogo.GRAY)

    # Desenha as linhas verticais
    for x in range(100, 600, 100):
        pygame.draw.line(self.screen, jogo.BLUE, (x, 150), (x, 550), 2)

    # Desenha as linhas horizontais
    for y in range(150, 600, 100):
        pygame.draw.line(self.screen, jogo.BLUE, (100, y), (500, y), 2)

    # Desenha as linhas diagonais
    pygame.draw.line(self.screen, jogo.BLUE, (100, 150), (500, 550), 2)
    pygame.draw.line(self.screen, jogo.BLUE, (500, 150), (100, 550), 2)

    pygame.draw.line(self.screen, jogo.BLUE, (100, 350), (300, 150), 2)
    pygame.draw.line(self.screen, jogo.BLUE, (500, 350), (300, 150), 2)

    pygame.draw.line(self.screen, jogo.BLUE, (100, 350), (300, 550), 2)
    pygame.draw.line(self.screen, jogo.BLUE, (500, 350), (300, 550), 2)

  def matrix_for_list(self, matrix):
    return [str(item) for sublist in matrix for item in sublist]

  # Função para renderizar e desenhar o texto
  def draw_piece(self, text, center):

    if text == 'C':
      pygame.draw.circle(self.screen, jogo.BLACK, center, 10, 0)

    elif text == 'T':
      pygame.draw.circle(self.screen, jogo.RED, center, 20, 0)

  def game_loop(self, matrix):

    # Textos para serem renderizados
    texts = self.matrix_for_list(matrix)

    # Renderiza e desenha cada texto nas respectivas posições
    positions = [(x, y) for y in range(150, 600, 100) for x in range(100, 600, 100)]
    [self.draw_piece(text, pos) for text, pos in zip(texts, positions)]

    jogo.drawScreen(self.screen, 0.1)
    jogo.drawScreen(self.screen)