# -*- coding: utf-8 -*-
"""bagha_chall game - gamesimulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mGGThwAqWWWUhSqY-gzEGtD3Tj_atEO-
"""

from point import *
from board import *
from engine import *
from dashboard import *
from _jogo import *
from gameboard import *

class GameSimulation:

  def __init__(self):
      self.board = Board()
      self.gameboard = GameBoard()
      self.dashboard = None
      self.engine = None
      self.choice = " "
      self.move_choice = " "

      self.goat_heuristics_list = [
          "Maximizar a Oportunidade de Movimentos",
          "Maximizar a Oportunidade de Espaços Fechados",
          "Minimizar Capturas",
          "Maximizar Proteção",
          "Posicionar no Centro",
          "Evitar Diagonais"
      ]

      self.tiger_heuristics_list = [
          "Maximizar a Oportunidade de Movimentos",
          "Maximizar a Mobilidade dos Tigres",
          "Maximizar a Morte das Cabras",
          "Maximizar Capturas",
          "Ocupar Linhas Importantes",
          "Evitar Encurralamento",
          "Atacar em Grupo"
      ]

  def display_dashboard(self):
    # Captura a escolha do jogador
    print("Bem-vindo ao jogo Bagha-Chall!")

    print("")

    print("Escolha uma opção:")
    print("1. Jogar como Cabras")
    print("2. Jogar como Tigres")
    print("3. Jogo Automático")

    print("")
    self.choice = input("Digite o número correspondente à sua escolha: ")

    while self.choice not in ["1", "2", "3"]:

      print("\033[1mEscolha inválida\033[0m. Por favor, escolha 1, 2 ou 3.")
      print("")

      self.choice = input("Digite o número correspondente à sua escolha: ")

      if self.choice in ["1", "2", "3"]:
        break

    # Inicializa o dashboard
    if self.choice == "1":

      print("Você escolheu jogar como \033[1mCabras\033[0m!")
      print("")

      # Criação do dashboard
      self.dashboard = HeuristicsDashboard([],self.tiger_heuristics_list, width='600px')

    elif self.choice == "2":

      print("Você escolheu jogar como \033[1mTigres\033[0m!")
      print("")

      # Criação do dashboard
      self.dashboard = HeuristicsDashboard(self.goat_heuristics_list, [], width='600px')

    elif self.choice == "3":

      print("Você escolheu assistir a um \033[1mJogo Automático\033[0m!")
      print("")

      # Criação do dashboard
      self.dashboard = HeuristicsDashboard(self.goat_heuristics_list, self.tiger_heuristics_list)

  def run_dashboard_heuristic(self):
    self.display_dashboard()
    self.dashboard.display_dashboard()

  def init_game_board(self):
    self.gameboard.install_font()
    self.gameboard.game_layout()
    self.gameboard.game_loop(self.board.game_board)

  def print_moves_table(self, moves):
      """
      Gera e exibe uma tabela formatada com opções numeradas para os movimentos.

      :param moves: Lista de dicionários com os movimentos (e.g., [{'from': 'A1', 'to': 'B1', 'type': 'MOVE'}]).
      """

      # Configuração do cabeçalho e largura das colunas
      header_mov = "Movimentos Válidos"
      header_tipo = "Tipo de Movimento"
      col_width_mov = 20
      col_width_tipo = 15

      # Cabeçalho alinhado
      print(f"{'':4}{header_mov.ljust(col_width_mov)}|{header_tipo.ljust(col_width_tipo)}")

      # Barra de separação
      print("    " + "-" * (col_width_mov + col_width_tipo + 3))  # Inclui o espaço para a numeração

      # Corpo da tabela com numeração
      for i, move in enumerate(moves, start=1):
          if move['type'] == self.engine.board.MoveType.PLACE:
              movimento = f"{move['to']}".ljust(col_width_mov)
              tipo = f"{move['type'].name}".ljust(col_width_tipo)

          elif move['type'] == self.engine.board.MoveType.MOVE:
              movimento = f"{move['from']}->{move['to']}".ljust(col_width_mov)
              tipo = f"{move['type'].name}".ljust(col_width_tipo)

          elif move['type'] == self.engine.board.MoveType.CAPTURE:
              movimento = f"{move['from']}->{move['to']}".ljust(col_width_mov)
              tipo = f"{move['type'].name}".ljust(col_width_tipo)

          # Imprime a linha formatada com numeração
          print(f"{i:<4}{movimento}|{tipo}")

  def run_game_simulation(self):
    """ Roda a simulação do jogo até que haja um vencedor. """

    self.engine = Engine(self.dashboard.selected_goat_heuristics, self.dashboard.selected_tiger_heuristics)

    while not self.engine.board.winner:
      if self.choice == "1":
        if self.engine.board.turn == self.engine.board.Player.GOAT:

          moves = self.engine.board.generate_move_list()
          self.print_moves_table(moves)

          print("")
          self.move_choice = input("Digite o número correspondente ao movimento escolhido: ")

          while self.move_choice not in [str(i) for i in range(1, len(moves) + 1)]:

            print(f"\033[1mEscolha inválida\033[0m. Por favor, escolha um número entre 1 e {len(moves)}.")
            print("")

            self.move_choice = input("Digite o número correspondente ao movimento escolhido: ")

            if self.move_choice in [str(i) for i in range(1, len(moves) + 1)]:
              break

          self.engine.board.make_move(moves[int(self.move_choice) - 1])
          # self.engine.board.show()
          self.gameboard.game_layout()
          self.gameboard.game_loop(self.engine.board.game_board)

        else:
          self.engine.make_best_move()
          # self.engine.board.show()
          self.gameboard.game_layout()
          self.gameboard.game_loop(self.engine.board.game_board)

      elif self.choice == "2":
        if self.engine.board.turn == self.engine.board.Player.TIGER:

          moves = self.engine.board.generate_move_list()
          self.print_moves_table(moves)

          print("")
          self.move_choice = input("Digite o número correspondente ao movimento escolhido: ")

          while self.move_choice not in [str(i) for i in range(1, len(moves) + 1)]:

            print(f"\033[1mEscolha inválida\033[0m. Por favor, escolha um número entre 1 e {len(moves)}.")
            print("")

            self.move_choice = input("Digite o número correspondente ao movimento escolhido: ")

            if self.move_choice in [str(i) for i in range(1, len(moves) + 1)]:
              break

          self.engine.board.make_move(moves[int(self.move_choice) - 1])
          # self.engine.board.show()
          self.gameboard.game_layout()
          self.gameboard.game_loop(self.engine.board.game_board)

        else:
          self.engine.make_best_move()
          # self.engine.board.show()
          self.gameboard.game_layout()
          self.gameboard.game_loop(self.engine.board.game_board)

      else:
        self.engine.make_best_move()
        # self.engine.board.show()
        self.gameboard.game_layout()
        self.gameboard.game_loop(self.engine.board.game_board)

    print(f"Vencedor: {self.engine.board.winner.name}")